### ISSUE TITLE
SecurityError: The operation is insecure.

### ISSUE THREAD

**Issue by josemigallas** [sirLisko/zoomMEME#21]
Hi, great app! However I get this error from the web page when clicking on Save Image:

<img width="1440" alt="Screen Shot 2019-04-08 at 13 48 45" src="https://user-images.githubusercontent.com/11672286/55721999-33afb400-5a05-11e9-962b-f32d6ec5ba16.png">

**Comment by sirlisko** [comment]
Hi :)

Looking at the icons of your browser I guess you are using Firefox.
I double-checked and it seems everything is fine. Could it be some extension you have installed? 🤔

**Comment by josemigallas** [comment]
AdBlock might have been the only responsible however the error persist after turning it off. May be a CORS related issue? https://stackoverflow.com/q/16371316/5466997

**Comment by sirlisko** [comment]
It's weird because everything is kept in the frontend, now sure if `html2canvas` is doing any sort of sorcery under the hood  🤔

Just out of my curiosity, did you try to run it in private mode?

**Comment by josemigallas** [comment]
Well I can't explain how but it's working now.. for the record I did try in private mode, disabling all extensions: no luck... although it worked in Chrome.

I guess false alarm?

**Comment by sirlisko** [comment]
That's weird. I usually test in all the major browsers and it was just working, because of that I thought it was something related to an extension.

Well, closing this issue, let me know if this problem happens again :)
