### ISSUE TITLE
Problems with iOS portrait image

### ISSUE THREAD

**Issue by sirlisko** [sirLisko/zoomMEME#7]
Uploading portrait images (taken with iOS) is leading to wrong orientations in the final meme.

This image:
![unadjustednonraw_thumb_2cae](https://user-images.githubusercontent.com/435399/34360006-2c7a5c8a-ea5d-11e7-9358-bc8b579dc83f.jpg)

is producing this output:
![unadjustednonraw_thumb_2cac](https://user-images.githubusercontent.com/435399/34360007-2e781fe0-ea5d-11e7-8194-67fae87c5c8c.jpg)

**Comment by sirlisko** [comment]
The problem is related to the orientation set in the `exif` by iOS, and because of that the module `html2canvas` is using a wrong orientation for the images.

**Comment by sirLisko** [comment]
Related to https://github.com/niklasvh/html2canvas/issues/1422.
